name: PR Visual Tests Report

on:
  workflow_run:
    workflows: ['PR Visual Tests']
    types:
      - completed

jobs:
  comment:
    name: Create GitHub Comment
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.GRAVITY_UI_APP_ID }}
          private-key: ${{ secrets.GRAVITY_UI_APP_PRIVATE_KEY }}
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Extract PR Number
        id: pr
        run: echo "::set-output name=id::$(<pr/pr-id.txt)"
        shell: bash
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2.22.35
          arch: amd64
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
          AWS_DEFAULT_REGION: ru-central1
          AWS_EC2_METADATA_DISABLED: true
          PR_ID: ${{ steps.pr.outputs.id }}
        run: |
          for v in 17 18 19; do
            if [ -d "playwright-report-react${v}" ]; then
              aws s3 cp "playwright-report-react${v}" "s3://playwright-reports/charts/pulls/${PR_ID}/react${v}/" --endpoint-url=https://storage.yandexcloud.net --recursive
            fi
            if [ -d "playwright-report-perf-react${v}" ]; then
              aws s3 cp "playwright-report-perf-react${v}" "s3://playwright-reports/charts/pulls/${PR_ID}/react${v}/perf/" --endpoint-url=https://storage.yandexcloud.net --recursive
            fi
          done
        shell: bash
      - name: Create Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          number: ${{ steps.pr.outputs.id }}
          header: visual tests report
          message: |
            Visual Tests Reports:
            - React 17: [visual](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react17/index.html) · [perf](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react17/perf/index.html)
            - React 18: [visual](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react18/index.html) · [perf](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react18/perf/index.html)
            - React 19: [visual](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react19/index.html) · [perf](https://storage.yandexcloud.net/playwright-reports/charts/pulls/${{ steps.pr.outputs.id }}/react19/perf/index.html)
