name: PR Visual Tests

on:
  pull_request:

jobs:
  visual_tests:
    name: Visual Tests (React ${{ matrix.react }})
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-jammy
    strategy:
      fail-fast: false
      matrix:
        react: ['17', '18', '19']
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: npm ci
      - name: Install React ${{ matrix.react }}
        run: node scripts/install-react.mjs ${{ matrix.react }}
      - name: Run Visual Tests
        run: npm run playwright:visual
        env:
          CI: 'true'
          REACT_VERSION: ${{ matrix.react }}
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-react${{ matrix.react }}
          path: ./playwright-report
          retention-days: 1

  visual_tests_perf:
    name: Visual Tests Performance (React ${{ matrix.react }})
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-jammy
    strategy:
      fail-fast: false
      matrix:
        react: ['17', '18', '19']
    steps:
      - uses: actions/checkout@v4
      - name: Install Packages
        run: npm ci
      - name: Install React ${{ matrix.react }}
        run: node scripts/install-react.mjs ${{ matrix.react }}
      - name: Run Performance Tests
        run: npm run playwright:perf
        env:
          CI: 'true'
          REACT_VERSION: ${{ matrix.react }}
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-perf-react${{ matrix.react }}
          path: ./playwright-report
          retention-days: 1

  save_pr:
    name: Save PR ID
    runs-on: ubuntu-latest
    steps:
      - name: Save PR ID
        run: echo "${{ github.event.pull_request.number }}" > ./pr-id.txt
      - name: Upload PR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr
          path: ./pr-id.txt
